#include "format/formatter.h"

#include <stdio.h>

#include "core/mnemonic.h"
#include "core/register.h"

#define MN(x) X86DEC_MNEMONIC_##x
#define RG(x) X86DEC_REG_##x

static const char* const x86dec_mnemonic_texts[X86DEC_MNEMONIC_COUNT] = {
  [MN(INVALID)] = "invalid",
  [MN(NOP)] = "nop",
  [MN(PAUSE)] = "pause",
  [MN(MOV)] = "mov",
  [MN(MOVSX)] = "movsx",
  [MN(MOVSXD)] = "movsxd",
  [MN(MOVZX)] = "movzx",
  [MN(LEA)] = "lea",
  [MN(XCHG)] = "xchg",
  [MN(BSWAP)] = "bswap",
  [MN(XADD)] = "xadd",
  [MN(CMPXCHG)] = "cmpxchg",
  [MN(CMPXCHG8B)] = "cmpxchg8b",
  [MN(CMPXCHG16B)] = "cmpxchg16b",
  [MN(ADD)] = "add",
  [MN(OR)] = "or",
  [MN(ADC)] = "adc",
  [MN(SBB)] = "sbb",
  [MN(AND)] = "and",
  [MN(SUB)] = "sub",
  [MN(XOR)] = "xor",
  [MN(CMP)] = "cmp",
  [MN(TEST)] = "test",
  [MN(INC)] = "inc",
  [MN(DEC)] = "dec",
  [MN(NEG)] = "neg",
  [MN(NOT)] = "not",
  [MN(MUL)] = "mul",
  [MN(IMUL)] = "imul",
  [MN(DIV)] = "div",
  [MN(IDIV)] = "idiv",
  [MN(SHL)] = "shl",
  [MN(SAL)] = "sal",
  [MN(SHR)] = "shr",
  [MN(SAR)] = "sar",
  [MN(ROL)] = "rol",
  [MN(ROR)] = "ror",
  [MN(RCL)] = "rcl",
  [MN(RCR)] = "rcr",
  [MN(SHLD)] = "shld",
  [MN(SHRD)] = "shrd",
  [MN(BT)] = "bt",
  [MN(BTS)] = "bts",
  [MN(BTR)] = "btr",
  [MN(BTC)] = "btc",
  [MN(BSF)] = "bsf",
  [MN(BSR)] = "bsr",
  [MN(TZCNT)] = "tzcnt",
  [MN(LZCNT)] = "lzcnt",
  [MN(PUSH)] = "push",
  [MN(POP)] = "pop",
  [MN(PUSHF)] = "pushf",
  [MN(POPF)] = "popf",
  [MN(CALL)] = "call",
  [MN(RET)] = "ret",
  [MN(RETF)] = "retf",
  [MN(JMP)] = "jmp",
  [MN(JO)] = "jo",
  [MN(JNO)] = "jno",
  [MN(JB)] = "jb",
  [MN(JNB)] = "jnb",
  [MN(JZ)] = "jz",
  [MN(JNZ)] = "jnz",
  [MN(JBE)] = "jbe",
  [MN(JA)] = "ja",
  [MN(JS)] = "js",
  [MN(JNS)] = "jns",
  [MN(JP)] = "jp",
  [MN(JNP)] = "jnp",
  [MN(JL)] = "jl",
  [MN(JNL)] = "jnl",
  [MN(JLE)] = "jle",
  [MN(JG)] = "jg",
  [MN(LOOP)] = "loop",
  [MN(LOOPE)] = "loope",
  [MN(LOOPNE)] = "loopne",
  [MN(JCXZ)] = "jcxz",
  [MN(JECXZ)] = "jecxz",
  [MN(JRCXZ)] = "jrcxz",
  [MN(SETO)] = "seto",
  [MN(SETNO)] = "setno",
  [MN(SETB)] = "setb",
  [MN(SETNB)] = "setnb",
  [MN(SETZ)] = "setz",
  [MN(SETNZ)] = "setnz",
  [MN(SETBE)] = "setbe",
  [MN(SETA)] = "seta",
  [MN(SETS)] = "sets",
  [MN(SETNS)] = "setns",
  [MN(SETP)] = "setp",
  [MN(SETNP)] = "setnp",
  [MN(SETL)] = "setl",
  [MN(SETNL)] = "setnl",
  [MN(SETLE)] = "setle",
  [MN(SETG)] = "setg",
  [MN(CMOVO)] = "cmovo",
  [MN(CMOVNO)] = "cmovno",
  [MN(CMOVB)] = "cmovb",
  [MN(CMOVNB)] = "cmovnb",
  [MN(CMOVZ)] = "cmovz",
  [MN(CMOVNZ)] = "cmovnz",
  [MN(CMOVBE)] = "cmovbe",
  [MN(CMOVA)] = "cmova",
  [MN(CMOVS)] = "cmovs",
  [MN(CMOVNS)] = "cmovns",
  [MN(CMOVP)] = "cmovp",
  [MN(CMOVNP)] = "cmovnp",
  [MN(CMOVL)] = "cmovl",
  [MN(CMOVNL)] = "cmovnl",
  [MN(CMOVLE)] = "cmovle",
  [MN(CMOVG)] = "cmovg",
  [MN(INT)] = "int",
  [MN(INT1)] = "int1",
  [MN(INT3)] = "int3",
  [MN(INTO)] = "into",
  [MN(IRET)] = "iret",
  [MN(IRETD)] = "iretd",
  [MN(IRETQ)] = "iretq",
  [MN(HLT)] = "hlt",
  [MN(CMC)] = "cmc",
  [MN(CLC)] = "clc",
  [MN(STC)] = "stc",
  [MN(CLI)] = "cli",
  [MN(STI)] = "sti",
  [MN(CLD)] = "cld",
  [MN(STD)] = "std",
  [MN(LEAVE)] = "leave",
  [MN(ENTER)] = "enter",
  [MN(XLAT)] = "xlat",
  [MN(CBW)] = "cbw",
  [MN(CWDE)] = "cwde",
  [MN(CDQE)] = "cdqe",
  [MN(CWD)] = "cwd",
  [MN(CDQ)] = "cdq",
  [MN(CQO)] = "cqo",
  [MN(SAHF)] = "sahf",
  [MN(LAHF)] = "lahf",
  [MN(MOVSB)] = "movsb",
  [MN(MOVSW)] = "movsw",
  [MN(MOVSD)] = "movsd",
  [MN(MOVSQ)] = "movsq",
  [MN(CMPSB)] = "cmpsb",
  [MN(CMPSW)] = "cmpsw",
  [MN(CMPSD)] = "cmpsd",
  [MN(CMPSQ)] = "cmpsq",
  [MN(STOSB)] = "stosb",
  [MN(STOSW)] = "stosw",
  [MN(STOSD)] = "stosd",
  [MN(STOSQ)] = "stosq",
  [MN(LODSB)] = "lodsb",
  [MN(LODSW)] = "lodsw",
  [MN(LODSD)] = "lodsd",
  [MN(LODSQ)] = "lodsq",
  [MN(SCASB)] = "scasb",
  [MN(SCASW)] = "scasw",
  [MN(SCASD)] = "scasd",
  [MN(SCASQ)] = "scasq",
  [MN(IN)] = "in",
  [MN(OUT)] = "out",
  [MN(EMMS)] = "emms",
  [MN(CPUID)] = "cpuid",
  [MN(RDTSC)] = "rdtsc",
  [MN(RDTSCP)] = "rdtscp",
  [MN(RDRAND)] = "rdrand",
  [MN(RDSEED)] = "rdseed",
  [MN(RDPID)] = "rdpid",
  [MN(SYSCALL)] = "syscall",
  [MN(SYSRET)] = "sysret",
  [MN(SYSENTER)] = "sysenter",
  [MN(SYSEXIT)] = "sysexit",
  [MN(SWAPGS)] = "swapgs",
  [MN(RDMSR)] = "rdmsr",
  [MN(WRMSR)] = "wrmsr",
  [MN(RDPMC)] = "rdpmc",
  [MN(CLTS)] = "clts",
  [MN(INVD)] = "invd",
  [MN(WBINVD)] = "wbinvd",
  [MN(UD0)] = "ud0",
  [MN(UD1)] = "ud1",
  [MN(UD2)] = "ud2",
  [MN(SGDT)] = "sgdt",
  [MN(SIDT)] = "sidt",
  [MN(LGDT)] = "lgdt",
  [MN(LIDT)] = "lidt",
  [MN(SMSW)] = "smsw",
  [MN(LMSW)] = "lmsw",
  [MN(INVLPG)] = "invlpg",
  [MN(SLDT)] = "sldt",
  [MN(STR)] = "str",
  [MN(LLDT)] = "lldt",
  [MN(LTR)] = "ltr",
  [MN(VERR)] = "verr",
  [MN(VERW)] = "verw",
  [MN(FXSAVE)] = "fxsave",
  [MN(FXRSTOR)] = "fxrstor",
  [MN(LDMXCSR)] = "ldmxcsr",
  [MN(STMXCSR)] = "stmxcsr",
  [MN(XSAVE)] = "xsave",
  [MN(XRSTOR)] = "xrstor",
  [MN(XSAVEOPT)] = "xsaveopt",
  [MN(CLFLUSH)] = "clflush",
  [MN(LFENCE)] = "lfence",
  [MN(MFENCE)] = "mfence",
  [MN(SFENCE)] = "sfence",
  [MN(PREFETCHNTA)] = "prefetchnta",
  [MN(PREFETCHT0)] = "prefetcht0",
  [MN(PREFETCHT1)] = "prefetcht1",
  [MN(PREFETCHT2)] = "prefetcht2",
  [MN(VMCALL)] = "vmcall",
  [MN(VMLAUNCH)] = "vmlaunch",
  [MN(VMRESUME)] = "vmresume",
  [MN(VMXOFF)] = "vmxoff",
  [MN(MONITOR)] = "monitor",
  [MN(MWAIT)] = "mwait",
  [MN(XGETBV)] = "xgetbv",
  [MN(XSETBV)] = "xsetbv",
  [MN(VMFUNC)] = "vmfunc",
  [MN(LFS)] = "lfs",
  [MN(LGS)] = "lgs",
  [MN(LSS)] = "lss",
  [MN(LAR)] = "lar",
  [MN(LSL)] = "lsl",
  [MN(VMREAD)] = "vmread",
  [MN(VMWRITE)] = "vmwrite",
  [MN(GETSEC)] = "getsec",
  [MN(POPCNT)] = "popcnt",
  [MN(ENDBR64)] = "endbr64",
  [MN(ENDBR32)] = "endbr32",
  [MN(WAIT)] = "wait",
  [MN(PUSHA)] = "pusha",
  [MN(PUSHAD)] = "pushad",
  [MN(POPA)] = "popa",
  [MN(POPAD)] = "popad",
  [MN(INSB)] = "insb",
  [MN(INSW)] = "insw",
  [MN(INSD)] = "insd",
  [MN(INSQ)] = "insq",
  [MN(OUTSB)] = "outsb",
  [MN(OUTSW)] = "outsw",
  [MN(OUTSD)] = "outsd",
  [MN(OUTSQ)] = "outsq",
  [MN(AAA)] = "aaa",
  [MN(AAS)] = "aas",
  [MN(DAA)] = "daa",
  [MN(DAS)] = "das",
  [MN(BOUND)] = "bound",
  [MN(ARPL)] = "arpl",
  [MN(LES)] = "les",
  [MN(LDS)] = "lds",
  [MN(AAM)] = "aam",
  [MN(AAD)] = "aad",
  [MN(SALC)] = "salc",
  [MN(FADD)] = "fadd",
  [MN(FADDP)] = "faddp",
  [MN(FIADD)] = "fiadd",
  [MN(FMUL)] = "fmul",
  [MN(FMULP)] = "fmulp",
  [MN(FIMUL)] = "fimul",
  [MN(FCOM)] = "fcom",
  [MN(FCOMP)] = "fcomp",
  [MN(FCOMPP)] = "fcompp",
  [MN(FCOMI)] = "fcomi",
  [MN(FCOMIP)] = "fcomip",
  [MN(FICOM)] = "ficom",
  [MN(FICOMP)] = "ficomp",
  [MN(FUCOM)] = "fucom",
  [MN(FUCOMP)] = "fucomp",
  [MN(FUCOMPP)] = "fucompp",
  [MN(FUCOMI)] = "fucomi",
  [MN(FUCOMIP)] = "fucomip",
  [MN(FSUB)] = "fsub",
  [MN(FSUBP)] = "fsubp",
  [MN(FISUB)] = "fisub",
  [MN(FSUBR)] = "fsubr",
  [MN(FSUBRP)] = "fsubrp",
  [MN(FISUBR)] = "fisubr",
  [MN(FDIV)] = "fdiv",
  [MN(FDIVP)] = "fdivp",
  [MN(FIDIV)] = "fidiv",
  [MN(FDIVR)] = "fdivr",
  [MN(FDIVRP)] = "fdivrp",
  [MN(FIDIVR)] = "fidivr",
  [MN(FLD)] = "fld",
  [MN(FILD)] = "fild",
  [MN(FBLD)] = "fbld",
  [MN(FST)] = "fst",
  [MN(FIST)] = "fist",
  [MN(FSTP)] = "fstp",
  [MN(FISTP)] = "fistp",
  [MN(FISTTP)] = "fisttp",
  [MN(FBSTP)] = "fbstp",
  [MN(FLDENV)] = "fldenv",
  [MN(FLDCW)] = "fldcw",
  [MN(FNSTENV)] = "fnstenv",
  [MN(FNSTCW)] = "fnstcw",
  [MN(FRSTOR)] = "frstor",
  [MN(FSAVE)] = "fsave",
  [MN(FNSTSW)] = "fnstsw",
  [MN(FCHS)] = "fchs",
  [MN(FABS)] = "fabs",
  [MN(FTST)] = "ftst",
  [MN(FXAM)] = "fxam",
  [MN(FLD1)] = "fld1",
  [MN(FLDL2T)] = "fldl2t",
  [MN(FLDL2E)] = "fldl2e",
  [MN(FLDPI)] = "fldpi",
  [MN(FLDLG2)] = "fldlg2",
  [MN(FLDLN2)] = "fldln2",
  [MN(FLDZ)] = "fldz",
  [MN(F2XM1)] = "f2xm1",
  [MN(FYL2X)] = "fyl2x",
  [MN(FPTAN)] = "fptan",
  [MN(FPATN)] = "fpatan",
  [MN(FXTRACT)] = "fxtract",
  [MN(FPREM1)] = "fprem1",
  [MN(FDECSTP)] = "fdecstp",
  [MN(FINCSTP)] = "fincstp",
  [MN(FPREM)] = "fprem",
  [MN(FYL2XP1)] = "fyl2xp1",
  [MN(FSQRT)] = "fsqrt",
  [MN(FSINCOS)] = "fsincos",
  [MN(FRNDINT)] = "frndint",
  [MN(FSCALE)] = "fscale",
  [MN(FSIN)] = "fsin",
  [MN(FCOS)] = "fcos",
  [MN(FNOP)] = "fnop",
  [MN(FXCH)] = "fxch",
  [MN(FCMOVB)] = "fcmovb",
  [MN(FCMOVE)] = "fcmove",
  [MN(FCMOVBE)] = "fcmovbe",
  [MN(FCMOVU)] = "fcmovu",
  [MN(FCMOVNB)] = "fcmovnb",
  [MN(FCMOVNE)] = "fcmovne",
  [MN(FCMOVNBE)] = "fcmovnbe",
  [MN(FCMOVNU)] = "fcmovnu",
  [MN(FNCLEX)] = "fnclex",
  [MN(FNINIT)] = "fninit",
  [MN(FNENI)] = "fneni",
  [MN(FNDISI)] = "fndisi",
  [MN(FNSETPM)] = "fnsetpm",
  [MN(FFREE)] = "ffree",
  [MN(FFREEP)] = "ffreep",
  [MN(PI2FW)] = "pi2fw",
  [MN(PI2FD)] = "pi2fd",
  [MN(PF2IW)] = "pf2iw",
  [MN(PF2ID)] = "pf2id",
  [MN(PFNACC)] = "pfnacc",
  [MN(PFPNACC)] = "pfpnacc",
  [MN(PFCMPGE)] = "pfcmpge",
  [MN(PFCMPGT)] = "pfcmpgt",
  [MN(PFCMPEQ)] = "pfcmpeq",
  [MN(PFMIN)] = "pfmin",
  [MN(PFRCP)] = "pfrcp",
  [MN(PFRSQRT)] = "pfrsqrt",
  [MN(PFRCPIT1)] = "pfrcpit1",
  [MN(PFRCPIT2)] = "pfrcpit2",
  [MN(PFRSQIT1)] = "pfrsqit1",
  [MN(PFSUB)] = "pfsub",
  [MN(PFSUBR)] = "pfsubr",
  [MN(PFADD)] = "pfadd",
  [MN(PFACC)] = "pfacc",
  [MN(PFMAX)] = "pfmax",
  [MN(PFMUL)] = "pfmul",
  [MN(PMULHRW)] = "pmulhrw",
  [MN(PSWAPD)] = "pswapd",
  [MN(PAVGUSB)] = "pavgusb",
  [MN(FEMMS)] = "femms",
  [MN(PREFETCH)] = "prefetch",
  [MN(PREFETCHW)] = "prefetchw",
  [MN(VMRUN)] = "vmrun",
  [MN(VMLOAD)] = "vmload",
  [MN(VMSAVE)] = "vmsave",
  [MN(CLGI)] = "clgi",
  [MN(STGI)] = "stgi",
  [MN(INVLPGA)] = "invlpga",
  [MN(MONITORX)] = "monitorx",
  [MN(MWAITX)] = "mwaitx",
  [MN(CLZERO)] = "clzero",
  [MN(RDPRU)] = "rdpru",
  [MN(SERIALIZE)] = "serialize",
  [MN(HRESET)] = "hreset",
  [MN(CLUI)] = "clui",
  [MN(STUI)] = "stui",
  [MN(TESTUI)] = "testui",
  [MN(UIRET)] = "uiret",
  [MN(SENDUIPI)] = "senduipi",
  [MN(RDSSP)] = "rdssp",
  [MN(SAVEPREVSSP)] = "saveprevssp",
  [MN(RSTORSSP)] = "rstorssp",
  [MN(WRMSRNS)] = "wrmsrns",
  [MN(PCONFIG)] = "pconfig",
  [MN(ENCLV)] = "enclv",
  [MN(ENCLS)] = "encls",
  [MN(ENCLU)] = "enclu",
  [MN(RSM)] = "rsm",
  [MN(AESENC)] = "aesenc",
  [MN(AESENCLAST)] = "aesenclast",
  [MN(AESDEC)] = "aesdec",
  [MN(AESDECLAST)] = "aesdeclast",
  [MN(AESIMC)] = "aesimc",
  [MN(AESKEYGENASSIST)] = "aeskeygenassist",
  [MN(PCLMULQDQ)] = "pclmulqdq",
  [MN(CRC32)] = "crc32",
  [MN(SHA1NEXTE)] = "sha1nexte",
  [MN(SHA1MSG1)] = "sha1msg1",
  [MN(SHA1MSG2)] = "sha1msg2",
  [MN(SHA1RNDS4)] = "sha1rnds4",
  [MN(SHA256RNDS2)] = "sha256rnds2",
  [MN(SHA256MSG1)] = "sha256msg1",
  [MN(SHA256MSG2)] = "sha256msg2",
  [MN(MOVUPS)] = "movups",
  [MN(MOVUPD)] = "movupd",
  [MN(MOVSS)] = "movss",
  [MN(MOVSD_SSE)] = "movsd",
  [MN(MOVAPS)] = "movaps",
  [MN(MOVAPD)] = "movapd",
  [MN(MOVLPS)] = "movlps",
  [MN(MOVLPD)] = "movlpd",
  [MN(MOVHPS)] = "movhps",
  [MN(MOVHPD)] = "movhpd",
  [MN(MOVLHPS)] = "movlhps",
  [MN(MOVQ)] = "movq",
  [MN(MOVD)] = "movd",
  [MN(MOVDQA)] = "movdqa",
  [MN(MOVDQU)] = "movdqu",
  [MN(MOVMSKPS)] = "movmskps",
  [MN(MOVMSKPD)] = "movmskpd",
  [MN(MOVNTPS)] = "movntps",
  [MN(MOVNTPD)] = "movntpd",
  [MN(MOVNTDQ)] = "movntdq",
  [MN(MOVNTI)] = "movnti",
  [MN(MOVNTQ)] = "movntq",
  [MN(MASKMOVQ)] = "maskmovq",
  [MN(MASKMOVDQU)] = "maskmovdqu",
  [MN(LDDQU)] = "lddqu",
  [MN(MOVDQ2Q)] = "movdq2q",
  [MN(MOVQ2DQ)] = "movq2dq",
  [MN(ADDPS)] = "addps",
  [MN(ADDPD)] = "addpd",
  [MN(ADDSS)] = "addss",
  [MN(ADDSD)] = "addsd",
  [MN(SUBPS)] = "subps",
  [MN(SUBPD)] = "subpd",
  [MN(SUBSS)] = "subss",
  [MN(SUBSD)] = "subsd",
  [MN(MULPS)] = "mulps",
  [MN(MULPD)] = "mulpd",
  [MN(MULSS)] = "mulss",
  [MN(MULSD)] = "mulsd",
  [MN(DIVPS)] = "divps",
  [MN(DIVPD)] = "divpd",
  [MN(DIVSS)] = "divss",
  [MN(DIVSD)] = "divsd",
  [MN(SQRTPS)] = "sqrtps",
  [MN(SQRTPD)] = "sqrtpd",
  [MN(SQRTSS)] = "sqrtss",
  [MN(SQRTSD)] = "sqrtsd",
  [MN(MAXPS)] = "maxps",
  [MN(MAXPD)] = "maxpd",
  [MN(MAXSS)] = "maxss",
  [MN(MAXSD)] = "maxsd",
  [MN(MINPS)] = "minps",
  [MN(MINPD)] = "minpd",
  [MN(MINSS)] = "minss",
  [MN(MINSD)] = "minsd",
  [MN(RCPPS)] = "rcpps",
  [MN(RCPSS)] = "rcpss",
  [MN(RSQRTPS)] = "rsqrtps",
  [MN(RSQRTSS)] = "rsqrtss",
  [MN(ANDPS)] = "andps",
  [MN(ANDPD)] = "andpd",
  [MN(ANDNPS)] = "andnps",
  [MN(ANDNPD)] = "andnpd",
  [MN(ORPS)] = "orps",
  [MN(ORPD)] = "orpd",
  [MN(XORPS)] = "xorps",
  [MN(XORPD)] = "xorpd",
  [MN(CMPPS)] = "cmpps",
  [MN(CMPPD)] = "cmppd",
  [MN(CMPSS)] = "cmpss",
  [MN(CMPSD_SSE)] = "cmpsd",
  [MN(COMISS)] = "comiss",
  [MN(UCOMISS)] = "ucomiss",
  [MN(COMISD)] = "comisd",
  [MN(UCOMISD)] = "ucomisd",
  [MN(CVTPI2PS)] = "cvtpi2ps",
  [MN(CVTPI2PD)] = "cvtpi2pd",
  [MN(CVTSI2SS)] = "cvtsi2ss",
  [MN(CVTSI2SD)] = "cvtsi2sd",
  [MN(CVTTPS2PI)] = "cvttps2pi",
  [MN(CVTTPD2PI)] = "cvttpd2pi",
  [MN(CVTTSS2SI)] = "cvttss2si",
  [MN(CVTTSD2SI)] = "cvttsd2si",
  [MN(CVTPS2PI)] = "cvtps2pi",
  [MN(CVTPD2PI)] = "cvtpd2pi",
  [MN(CVTSS2SI)] = "cvtss2si",
  [MN(CVTSD2SI)] = "cvtsd2si",
  [MN(CVTDQ2PS)] = "cvtdq2ps",
  [MN(CVTDQ2PD)] = "cvtdq2pd",
  [MN(CVTPS2DQ)] = "cvtps2dq",
  [MN(CVTPD2DQ)] = "cvtpd2dq",
  [MN(CVTTPS2DQ)] = "cvttps2dq",
  [MN(CVTTPD2DQ)] = "cvttpd2dq",
  [MN(CVTPS2PD)] = "cvtps2pd",
  [MN(CVTPD2PS)] = "cvtpd2ps",
  [MN(CVTSS2SD)] = "cvtss2sd",
  [MN(CVTSD2SS)] = "cvtsd2ss",
  [MN(UNPCKLPS)] = "unpcklps",
  [MN(UNPCKHPS)] = "unpckhps",
  [MN(UNPCKLPD)] = "unpcklpd",
  [MN(UNPCKHPD)] = "unpckhpd",
  [MN(SHUFPS)] = "shufps",
  [MN(SHUFPD)] = "shufpd",
  [MN(PUNPCKLBW)] = "punpcklbw",
  [MN(PUNPCKLWD)] = "punpcklwd",
  [MN(PUNPCKLDQ)] = "punpckldq",
  [MN(PACKSSWB)] = "packsswb",
  [MN(PCMPGTB)] = "pcmpgtb",
  [MN(PCMPGTW)] = "pcmpgtw",
  [MN(PCMPGTD)] = "pcmpgtd",
  [MN(PACKUSWB)] = "packuswb",
  [MN(PUNPCKHBW)] = "punpckhbw",
  [MN(PUNPCKHWD)] = "punpckhwd",
  [MN(PUNPCKHDQ)] = "punpckhdq",
  [MN(PACKSSDW)] = "packssdw",
  [MN(PUNPCKLQDQ)] = "punpcklqdq",
  [MN(PUNPCKHQDQ)] = "punpckhqdq",
  [MN(PSHUFW)] = "pshufw",
  [MN(PSHUFHW)] = "pshufhw",
  [MN(PSHUFLW)] = "pshuflw",
  [MN(PSHUFD)] = "pshufd",
  [MN(PSRLW)] = "psrlw",
  [MN(PSRLD)] = "psrld",
  [MN(PSRLQ)] = "psrlq",
  [MN(PSRAW)] = "psraw",
  [MN(PSRAD)] = "psrad",
  [MN(PSLLW)] = "psllw",
  [MN(PSLLD)] = "pslld",
  [MN(PSLLQ)] = "psllq",
  [MN(PSRLDQ)] = "psrldq",
  [MN(PSLLDQ)] = "pslldq",
  [MN(PCMPEQB)] = "pcmpeqb",
  [MN(PCMPEQW)] = "pcmpeqw",
  [MN(PCMPEQD)] = "pcmpeqd",
  [MN(PADDQ)] = "paddq",
  [MN(PADDB)] = "paddb",
  [MN(PADDW)] = "paddw",
  [MN(PADDD)] = "paddd",
  [MN(PMULLW)] = "pmullw",
  [MN(PMULHW)] = "pmulhw",
  [MN(PMULHUW)] = "pmulhuw",
  [MN(PMULUDQ)] = "pmuludq",
  [MN(PMADDWD)] = "pmaddwd",
  [MN(PSADBW)] = "psadbw",
  [MN(PSUBUSB)] = "psubusb",
  [MN(PSUBUSW)] = "psubusw",
  [MN(PADDUSB)] = "paddusb",
  [MN(PADDUSW)] = "paddusw",
  [MN(PSUBSB)] = "psubsb",
  [MN(PSUBSW)] = "psubsw",
  [MN(PADDSB)] = "paddsb",
  [MN(PADDSW)] = "paddsw",
  [MN(PSUBB)] = "psubb",
  [MN(PSUBW)] = "psubw",
  [MN(PSUBD)] = "psubd",
  [MN(PSUBQ)] = "psubq",
  [MN(PAND)] = "pand",
  [MN(PANDN)] = "pandn",
  [MN(POR)] = "por",
  [MN(PXOR)] = "pxor",
  [MN(PAVGB)] = "pavgb",
  [MN(PAVGW)] = "pavgw",
  [MN(PMINUB)] = "pminub",
  [MN(PMAXUB)] = "pmaxub",
  [MN(PMINSW)] = "pminsw",
  [MN(PMAXSW)] = "pmaxsw",
  [MN(PMOVMSKB)] = "pmovmskb",
  [MN(HADDPS)] = "haddps",
  [MN(HADDPD)] = "haddpd",
  [MN(HSUBPS)] = "hsubps",
  [MN(HSUBPD)] = "hsubpd",
  [MN(ADDSUBPS)] = "addsubps",
  [MN(ADDSUBPD)] = "addsubpd"
};

static const char* const x86dec_register_texts[X86DEC_REG_COUNT] = {
  [RG(NONE)] = "none",
  [RG(RAX)] = "rax",
  [RG(RCX)] = "rcx",
  [RG(RDX)] = "rdx",
  [RG(RBX)] = "rbx",
  [RG(RSP)] = "rsp",
  [RG(RBP)] = "rbp",
  [RG(RSI)] = "rsi",
  [RG(RDI)] = "rdi",
  [RG(R8)] = "r8",
  [RG(R9)] = "r9",
  [RG(R10)] = "r10",
  [RG(R11)] = "r11",
  [RG(R12)] = "r12",
  [RG(R13)] = "r13",
  [RG(R14)] = "r14",
  [RG(R15)] = "r15",
  [RG(EAX)] = "eax",
  [RG(ECX)] = "ecx",
  [RG(EDX)] = "edx",
  [RG(EBX)] = "ebx",
  [RG(ESP)] = "esp",
  [RG(EBP)] = "ebp",
  [RG(ESI)] = "esi",
  [RG(EDI)] = "edi",
  [RG(R8D)] = "r8d",
  [RG(R9D)] = "r9d",
  [RG(R10D)] = "r10d",
  [RG(R11D)] = "r11d",
  [RG(R12D)] = "r12d",
  [RG(R13D)] = "r13d",
  [RG(R14D)] = "r14d",
  [RG(R15D)] = "r15d",
  [RG(AX)] = "ax",
  [RG(CX)] = "cx",
  [RG(DX)] = "dx",
  [RG(BX)] = "bx",
  [RG(SP)] = "sp",
  [RG(BP)] = "bp",
  [RG(SI)] = "si",
  [RG(DI)] = "di",
  [RG(R8W)] = "r8w",
  [RG(R9W)] = "r9w",
  [RG(R10W)] = "r10w",
  [RG(R11W)] = "r11w",
  [RG(R12W)] = "r12w",
  [RG(R13W)] = "r13w",
  [RG(R14W)] = "r14w",
  [RG(R15W)] = "r15w",
  [RG(AL)] = "al",
  [RG(CL)] = "cl",
  [RG(DL)] = "dl",
  [RG(BL)] = "bl",
  [RG(SPL)] = "spl",
  [RG(BPL)] = "bpl",
  [RG(SIL)] = "sil",
  [RG(DIL)] = "dil",
  [RG(R8B)] = "r8b",
  [RG(R9B)] = "r9b",
  [RG(R10B)] = "r10b",
  [RG(R11B)] = "r11b",
  [RG(R12B)] = "r12b",
  [RG(R13B)] = "r13b",
  [RG(R14B)] = "r14b",
  [RG(R15B)] = "r15b",
  [RG(AH)] = "ah",
  [RG(CH)] = "ch",
  [RG(DH)] = "dh",
  [RG(BH)] = "bh",
  [RG(IP)] = "ip",
  [RG(EIP)] = "eip",
  [RG(RIP)] = "rip",
  [RG(ES)] = "es",
  [RG(CS)] = "cs",
  [RG(SS)] = "ss",
  [RG(DS)] = "ds",
  [RG(FS)] = "fs",
  [RG(GS)] = "gs",
  [RG(CR0)] = "cr0",
  [RG(CR1)] = "cr1",
  [RG(CR2)] = "cr2",
  [RG(CR3)] = "cr3",
  [RG(CR4)] = "cr4",
  [RG(CR5)] = "cr5",
  [RG(CR6)] = "cr6",
  [RG(CR7)] = "cr7",
  [RG(CR8)] = "cr8",
  [RG(CR9)] = "cr9",
  [RG(CR10)] = "cr10",
  [RG(CR11)] = "cr11",
  [RG(CR12)] = "cr12",
  [RG(CR13)] = "cr13",
  [RG(CR14)] = "cr14",
  [RG(CR15)] = "cr15",
  [RG(DR0)] = "dr0",
  [RG(DR1)] = "dr1",
  [RG(DR2)] = "dr2",
  [RG(DR3)] = "dr3",
  [RG(DR4)] = "dr4",
  [RG(DR5)] = "dr5",
  [RG(DR6)] = "dr6",
  [RG(DR7)] = "dr7",
  [RG(ST0)] = "st0",
  [RG(ST1)] = "st1",
  [RG(ST2)] = "st2",
  [RG(ST3)] = "st3",
  [RG(ST4)] = "st4",
  [RG(ST5)] = "st5",
  [RG(ST6)] = "st6",
  [RG(ST7)] = "st7",
  [RG(MM0)] = "mm0",
  [RG(MM1)] = "mm1",
  [RG(MM2)] = "mm2",
  [RG(MM3)] = "mm3",
  [RG(MM4)] = "mm4",
  [RG(MM5)] = "mm5",
  [RG(MM6)] = "mm6",
  [RG(MM7)] = "mm7",
  [RG(XMM0)] = "xmm0",
  [RG(XMM1)] = "xmm1",
  [RG(XMM2)] = "xmm2",
  [RG(XMM3)] = "xmm3",
  [RG(XMM4)] = "xmm4",
  [RG(XMM5)] = "xmm5",
  [RG(XMM6)] = "xmm6",
  [RG(XMM7)] = "xmm7",
  [RG(XMM8)] = "xmm8",
  [RG(XMM9)] = "xmm9",
  [RG(XMM10)] = "xmm10",
  [RG(XMM11)] = "xmm11",
  [RG(XMM12)] = "xmm12",
  [RG(XMM13)] = "xmm13",
  [RG(XMM14)] = "xmm14",
  [RG(XMM15)] = "xmm15"
};

const char* x86dec_mnemonic_text(enum x86dec_mnemonic_e mnemonic)
{
  if ((unsigned)mnemonic >= X86DEC_MNEMONIC_COUNT) {
    return "invalid";
  }

  return x86dec_mnemonic_texts[mnemonic];
}

const char* x86dec_register_text(enum x86dec_register_e reg)
{
  if ((unsigned)reg >= X86DEC_REG_COUNT) {
    return "none";
  }

  return x86dec_register_texts[reg];
}

bool x86dec_format_insn(const X86decInsn* insn,
    const X86decOperand* operands, char* buffer, size_t size)
{
  char* cursor = buffer;
  size_t remaining = size;
  int written;
  uint8_t i;

  if (!insn || !buffer || !size) {
    return false;
  }

#define X86DEC_EMIT(...) do { written = snprintf(cursor, remaining, __VA_ARGS__); \
    if (written < 0 || (size_t)written >= remaining) { return false; } \
    cursor += written; remaining -= (size_t)written; } while (0)
  if (insn->flags & X86DEC_INSN_HAS_LOCK) {
    X86DEC_EMIT("lock ");
  }

  if ((insn->flags & X86DEC_INSN_HAS_REP) &&
      insn->mnemonic != X86DEC_MNEMONIC_PAUSE) {
    X86DEC_EMIT("rep ");
  }

  if (insn->flags & X86DEC_INSN_HAS_REPNE) {
    X86DEC_EMIT("repne ");
  }

  X86DEC_EMIT("%s", x86dec_mnemonic_text(insn->mnemonic));

  if (operands) {
    for (i = 0; i < insn->operand_count; i++) {
      const X86decOperand* op = &operands[i];

      X86DEC_EMIT(i ? ", " : " ");

      switch (op->type) {
        case X86DEC_OPERAND_REG:
          X86DEC_EMIT("%s", x86dec_register_text(op->reg));
          break;
        case X86DEC_OPERAND_IMM:
          X86DEC_EMIT("0x%llx", (unsigned long long)op->imm.value);
          break;
        case X86DEC_OPERAND_MEM: {
          const char* size_text = 0;
          unsigned long long magnitude;
          int is_first = 1;

          switch (op->size) {
            case 8:
              size_text = "byte ptr ";
              break;
            case 16:
              size_text = "word ptr ";
              break;
            case 32:
              size_text = "dword ptr ";
              break;
            case 64:
              size_text = "qword ptr ";
              break;
            case 48:
              size_text = "fword ptr ";
              break;
            case 80:
              size_text = "tbyte ptr ";
              break;
            default:
              break;
          }

          if (size_text) {
            X86DEC_EMIT("%s", size_text);
          }

          if (op->mem.segment != X86DEC_REG_NONE) {
            X86DEC_EMIT("%s:", x86dec_register_text(op->mem.segment));
          }

          X86DEC_EMIT("[");

          if (op->mem.base != X86DEC_REG_NONE) {
            X86DEC_EMIT("%s", x86dec_register_text(op->mem.base));
            is_first = 0;
          }

          if (op->mem.index != X86DEC_REG_NONE) {
            X86DEC_EMIT(is_first ? "%s" : "+%s",
                x86dec_register_text(op->mem.index));

            if (op->mem.scale > 1) {
              X86DEC_EMIT("*%u", op->mem.scale);
            }

            is_first = 0;
          }

          magnitude = op->mem.disp < 0
              ? 0ULL - (unsigned long long)op->mem.disp
              : (unsigned long long)op->mem.disp;

          if (op->mem.has_disp || is_first) {
            if (is_first) {
              X86DEC_EMIT(op->mem.disp < 0 ? "-0x%llx" : "0x%llx", magnitude);
            } else {
              X86DEC_EMIT(op->mem.disp < 0 ? "-0x%llx" : "+0x%llx", magnitude);
            }
          }

          X86DEC_EMIT("]");
          break;
        }
        default:
          X86DEC_EMIT("?");
          break;
      }
    }
  }

  return true;
#undef X86DEC_EMIT
}
