#include "tables.h"

#define M(x) X86DEC_MNEMONIC_##x
#define S(x) X86DEC_SHAPE_##x
#define V(mn, c, s0, s1, s2, mb) {(mn), (c), {(s0), (s1), (s2)}, (mb)}
#define NOVAR {0, 0, {0, 0, 0}, 0}
#define XX2(mn) V(mn, 2, S(XMM_REG), S(XMM_OR_MEM), S(NONE), 0)
#define MM2(mn) V(mn, 2, S(MM_REG), S(MM_OR_MEM), S(NONE), 0)

const X86decSseEntry x86dec_sse_alu[256] = {
[0x2A] = {
  .base = V(M(CVTPI2PS), 2, S(XMM_REG), S(MM_OR_MEM), S(NONE), 0),
  .variant_66 = NOVAR,
  .variant_f3 = V(M(CVTSI2SS), 2, S(XMM_REG), S(GPR_OR_MEM), S(NONE), 32),
  .variant_f2 = V(M(CVTSI2SD), 2, S(XMM_REG), S(GPR_OR_MEM), S(NONE), 64),
},
[0x2C] = {
  .base = V(M(CVTTPS2PI), 2, S(MM_REG), S(XMM_OR_MEM), S(NONE), 0),
  .variant_66 = NOVAR,
  .variant_f3 = V(M(CVTTSS2SI), 2, S(GPR_REG), S(XMM_OR_MEM), S(NONE), 32),
  .variant_f2 = V(M(CVTTSD2SI), 2, S(GPR_REG), S(XMM_OR_MEM), S(NONE), 64),
},
[0x2D] = {
  .base = V(M(CVTPS2PI), 2, S(MM_REG), S(XMM_OR_MEM), S(NONE), 0),
  .variant_66 = NOVAR,
  .variant_f3 = V(M(CVTSS2SI), 2, S(GPR_REG), S(XMM_OR_MEM), S(NONE), 32),
  .variant_f2 = V(M(CVTSD2SI), 2, S(GPR_REG), S(XMM_OR_MEM), S(NONE), 64),
},
[0x2E] = {
  .base = V(M(COMISS), 2, S(XMM_REG), S(XMM_OR_MEM), S(NONE), 32),
  .variant_66 = V(M(COMISD), 2, S(XMM_REG), S(XMM_OR_MEM), S(NONE), 64),
  .variant_f3 = NOVAR,
  .variant_f2 = NOVAR,
},
[0x2F] = {
  .base = V(M(UCOMISS), 2, S(XMM_REG), S(XMM_OR_MEM), S(NONE), 32),
  .variant_66 = V(M(UCOMISD), 2, S(XMM_REG), S(XMM_OR_MEM), S(NONE), 64),
  .variant_f3 = NOVAR,
  .variant_f2 = NOVAR,
},
[0x51] = {
  .base = XX2(M(SQRTPS)),
  .variant_66 = XX2(M(SQRTPD)),
  .variant_f3 = XX2(M(SQRTSS)),
  .variant_f2 = XX2(M(SQRTSD)),
},
[0x52] = {
  .base = XX2(M(RCPPS)),
  .variant_66 = NOVAR,
  .variant_f3 = XX2(M(RCPSS)),
  .variant_f2 = NOVAR,
},
[0x53] = {
  .base = XX2(M(RSQRTPS)),
  .variant_66 = NOVAR,
  .variant_f3 = XX2(M(RSQRTSS)),
  .variant_f2 = NOVAR,
},
[0x54] = {
  .base = XX2(M(ANDPS)),
  .variant_66 = XX2(M(ANDPD)),
  .variant_f3 = NOVAR,
  .variant_f2 = NOVAR,
},
[0x55] = {
  .base = XX2(M(ANDNPS)),
  .variant_66 = XX2(M(ANDNPD)),
  .variant_f3 = NOVAR,
  .variant_f2 = NOVAR,
},
[0x56] = {
  .base = XX2(M(ORPS)),
  .variant_66 = XX2(M(ORPD)),
  .variant_f3 = NOVAR,
  .variant_f2 = NOVAR,
},
[0x57] = {
  .base = XX2(M(XORPS)),
  .variant_66 = XX2(M(XORPD)),
  .variant_f3 = NOVAR,
  .variant_f2 = NOVAR,
},
[0x58] = {
  .base = XX2(M(ADDPS)),
  .variant_66 = XX2(M(ADDPD)),
  .variant_f3 = XX2(M(ADDSS)),
  .variant_f2 = XX2(M(ADDSD)),
},
[0x59] = {
  .base = XX2(M(MULPS)),
  .variant_66 = XX2(M(MULPD)),
  .variant_f3 = XX2(M(MULSS)),
  .variant_f2 = XX2(M(MULSD)),
},
[0x5A] = {
  .base = V(M(CVTPS2PD), 2, S(XMM_REG), S(XMM_OR_MEM), S(NONE), 64),
  .variant_66 = XX2(M(CVTPD2PS)),
  .variant_f3 = V(M(CVTSS2SD), 2, S(XMM_REG), S(XMM_OR_MEM), S(NONE), 32),
  .variant_f2 = V(M(CVTSD2SS), 2, S(XMM_REG), S(XMM_OR_MEM), S(NONE), 64),
},
[0x5B] = {
  .base = XX2(M(CVTDQ2PS)),
  .variant_66 = XX2(M(CVTPS2DQ)),
  .variant_f3 = XX2(M(CVTTPS2DQ)),
  .variant_f2 = NOVAR,
},
[0x5C] = {
  .base = XX2(M(SUBPS)),
  .variant_66 = XX2(M(SUBPD)),
  .variant_f3 = XX2(M(SUBSS)),
  .variant_f2 = XX2(M(SUBSD)),
},
[0x5D] = {
  .base = XX2(M(MINPS)),
  .variant_66 = XX2(M(MINPD)),
  .variant_f3 = XX2(M(MINSS)),
  .variant_f2 = XX2(M(MINSD)),
},
[0x5E] = {
  .base = XX2(M(DIVPS)),
  .variant_66 = XX2(M(DIVPD)),
  .variant_f3 = XX2(M(DIVSS)),
  .variant_f2 = XX2(M(DIVSD)),
},
[0x5F] = {
  .base = XX2(M(MAXPS)),
  .variant_66 = XX2(M(MAXPD)),
  .variant_f3 = XX2(M(MAXSS)),
  .variant_f2 = XX2(M(MAXSD)),
},
[0x60] = {
  .base = MM2(M(PUNPCKLBW)),
  .variant_66 = XX2(M(PUNPCKLBW)),
  .variant_f3 = NOVAR,
  .variant_f2 = NOVAR,
},
[0x61] = {
  .base = MM2(M(PUNPCKLWD)),
  .variant_66 = XX2(M(PUNPCKLWD)),
  .variant_f3 = NOVAR,
  .variant_f2 = NOVAR,
},
[0x62] = {
  .base = MM2(M(PUNPCKLDQ)),
  .variant_66 = XX2(M(PUNPCKLDQ)),
  .variant_f3 = NOVAR,
  .variant_f2 = NOVAR,
},
[0x63] = {
  .base = MM2(M(PACKSSWB)),
  .variant_66 = XX2(M(PACKSSWB)),
  .variant_f3 = NOVAR,
  .variant_f2 = NOVAR,
},
[0x64] = {
  .base = MM2(M(PCMPGTB)),
  .variant_66 = XX2(M(PCMPGTB)),
  .variant_f3 = NOVAR,
  .variant_f2 = NOVAR,
},
[0x65] = {
  .base = MM2(M(PCMPGTW)),
  .variant_66 = XX2(M(PCMPGTW)),
  .variant_f3 = NOVAR,
  .variant_f2 = NOVAR,
},
[0x66] = {
  .base = MM2(M(PCMPGTD)),
  .variant_66 = XX2(M(PCMPGTD)),
  .variant_f3 = NOVAR,
  .variant_f2 = NOVAR,
},
[0x67] = {
  .base = MM2(M(PACKUSWB)),
  .variant_66 = XX2(M(PACKUSWB)),
  .variant_f3 = NOVAR,
  .variant_f2 = NOVAR,
},
[0x68] = {
  .base = MM2(M(PUNPCKHBW)),
  .variant_66 = XX2(M(PUNPCKHBW)),
  .variant_f3 = NOVAR,
  .variant_f2 = NOVAR,
},
[0x69] = {
  .base = MM2(M(PUNPCKHWD)),
  .variant_66 = XX2(M(PUNPCKHWD)),
  .variant_f3 = NOVAR,
  .variant_f2 = NOVAR,
},
[0x6A] = {
  .base = MM2(M(PUNPCKHDQ)),
  .variant_66 = XX2(M(PUNPCKHDQ)),
  .variant_f3 = NOVAR,
  .variant_f2 = NOVAR,
},
[0x6B] = {
  .base = MM2(M(PACKSSDW)),
  .variant_66 = XX2(M(PACKSSDW)),
  .variant_f3 = NOVAR,
  .variant_f2 = NOVAR,
},
[0x6C] = {
  .base = NOVAR,
  .variant_66 = XX2(M(PUNPCKLQDQ)),
  .variant_f3 = NOVAR,
  .variant_f2 = NOVAR,
},
[0x6D] = {
  .base = NOVAR,
  .variant_66 = XX2(M(PUNPCKHQDQ)),
  .variant_f3 = NOVAR,
  .variant_f2 = NOVAR,
},
[0x70] = {
  .base = V(M(PSHUFW), 3, S(MM_REG), S(MM_OR_MEM), S(IMM8), 0),
  .variant_66 = V(M(PSHUFD), 3, S(XMM_REG), S(XMM_OR_MEM), S(IMM8), 0),
  .variant_f3 = V(M(PSHUFHW), 3, S(XMM_REG), S(XMM_OR_MEM), S(IMM8), 0),
  .variant_f2 = V(M(PSHUFLW), 3, S(XMM_REG), S(XMM_OR_MEM), S(IMM8), 0),
},
[0x74] = {
  .base = MM2(M(PCMPEQB)),
  .variant_66 = XX2(M(PCMPEQB)),
  .variant_f3 = NOVAR,
  .variant_f2 = NOVAR,
},
[0x75] = {
  .base = MM2(M(PCMPEQW)),
  .variant_66 = XX2(M(PCMPEQW)),
  .variant_f3 = NOVAR,
  .variant_f2 = NOVAR,
},
[0x76] = {
  .base = MM2(M(PCMPEQD)),
  .variant_66 = XX2(M(PCMPEQD)),
  .variant_f3 = NOVAR,
  .variant_f2 = NOVAR,
},
[0x7C] = {
  .base = NOVAR,
  .variant_66 = XX2(M(HADDPD)),
  .variant_f3 = NOVAR,
  .variant_f2 = XX2(M(HADDPS)),
},
[0x7D] = {
  .base = NOVAR,
  .variant_66 = XX2(M(HSUBPD)),
  .variant_f3 = NOVAR,
  .variant_f2 = XX2(M(HSUBPS)),
},
[0xC2] = {
  .base = V(M(CMPPS), 3, S(XMM_REG), S(XMM_OR_MEM), S(IMM8), 0),
  .variant_66 = V(M(CMPPD), 3, S(XMM_REG), S(XMM_OR_MEM), S(IMM8), 0),
  .variant_f3 = V(M(CMPSS), 3, S(XMM_REG), S(XMM_OR_MEM), S(IMM8), 0),
  .variant_f2 = V(M(CMPSD_SSE), 3, S(XMM_REG), S(XMM_OR_MEM), S(IMM8), 0),
},
[0xC6] = {
  .base = V(M(SHUFPS), 3, S(XMM_REG), S(XMM_OR_MEM), S(IMM8), 0),
  .variant_66 = V(M(SHUFPD), 3, S(XMM_REG), S(XMM_OR_MEM), S(IMM8), 0),
  .variant_f3 = NOVAR,
  .variant_f2 = NOVAR,
},
[0xD0] = {
  .base = NOVAR,
  .variant_66 = XX2(M(ADDSUBPD)),
  .variant_f3 = NOVAR,
  .variant_f2 = XX2(M(ADDSUBPS)),
},
[0xD1] = {
  .base = MM2(M(PSRLW)),
  .variant_66 = XX2(M(PSRLW)),
  .variant_f3 = NOVAR,
  .variant_f2 = NOVAR,
},
[0xD2] = {
  .base = MM2(M(PSRLD)),
  .variant_66 = XX2(M(PSRLD)),
  .variant_f3 = NOVAR,
  .variant_f2 = NOVAR,
},
[0xD3] = {
  .base = MM2(M(PSRLQ)),
  .variant_66 = XX2(M(PSRLQ)),
  .variant_f3 = NOVAR,
  .variant_f2 = NOVAR,
},
[0xD4] = {
  .base = MM2(M(PADDQ)),
  .variant_66 = XX2(M(PADDQ)),
  .variant_f3 = NOVAR,
  .variant_f2 = NOVAR,
},
[0xD5] = {
  .base = MM2(M(PMULLW)),
  .variant_66 = XX2(M(PMULLW)),
  .variant_f3 = NOVAR,
  .variant_f2 = NOVAR,
},
[0xD8] = {
  .base = MM2(M(PSUBUSB)),
  .variant_66 = XX2(M(PSUBUSB)),
  .variant_f3 = NOVAR,
  .variant_f2 = NOVAR,
},
[0xD9] = {
  .base = MM2(M(PSUBUSW)),
  .variant_66 = XX2(M(PSUBUSW)),
  .variant_f3 = NOVAR,
  .variant_f2 = NOVAR,
},
[0xDA] = {
  .base = MM2(M(PMINUB)),
  .variant_66 = XX2(M(PMINUB)),
  .variant_f3 = NOVAR,
  .variant_f2 = NOVAR,
},
[0xDB] = {
  .base = MM2(M(PAND)),
  .variant_66 = XX2(M(PAND)),
  .variant_f3 = NOVAR,
  .variant_f2 = NOVAR,
},
[0xDC] = {
  .base = MM2(M(PADDUSB)),
  .variant_66 = XX2(M(PADDUSB)),
  .variant_f3 = NOVAR,
  .variant_f2 = NOVAR,
},
[0xDD] = {
  .base = MM2(M(PADDUSW)),
  .variant_66 = XX2(M(PADDUSW)),
  .variant_f3 = NOVAR,
  .variant_f2 = NOVAR,
},
[0xDE] = {
  .base = MM2(M(PMAXUB)),
  .variant_66 = XX2(M(PMAXUB)),
  .variant_f3 = NOVAR,
  .variant_f2 = NOVAR,
},
[0xDF] = {
  .base = MM2(M(PANDN)),
  .variant_66 = XX2(M(PANDN)),
  .variant_f3 = NOVAR,
  .variant_f2 = NOVAR,
},
[0xE0] = {
  .base = MM2(M(PAVGB)),
  .variant_66 = XX2(M(PAVGB)),
  .variant_f3 = NOVAR,
  .variant_f2 = NOVAR,
},
[0xE1] = {
  .base = MM2(M(PSRAW)),
  .variant_66 = XX2(M(PSRAW)),
  .variant_f3 = NOVAR,
  .variant_f2 = NOVAR,
},
[0xE2] = {
  .base = MM2(M(PSRAD)),
  .variant_66 = XX2(M(PSRAD)),
  .variant_f3 = NOVAR,
  .variant_f2 = NOVAR,
},
[0xE3] = {
  .base = MM2(M(PAVGW)),
  .variant_66 = XX2(M(PAVGW)),
  .variant_f3 = NOVAR,
  .variant_f2 = NOVAR,
},
[0xE4] = {
  .base = MM2(M(PMULHUW)),
  .variant_66 = XX2(M(PMULHUW)),
  .variant_f3 = NOVAR,
  .variant_f2 = NOVAR,
},
[0xE5] = {
  .base = MM2(M(PMULHW)),
  .variant_66 = XX2(M(PMULHW)),
  .variant_f3 = NOVAR,
  .variant_f2 = NOVAR,
},
[0xE6] = {
  .base = V(M(CVTPI2PD), 2, S(XMM_REG), S(MM_OR_MEM), S(NONE), 0),
  .variant_66 = V(M(CVTTPD2DQ), 2, S(XMM_REG), S(XMM_OR_MEM), S(NONE), 0),
  .variant_f3 = XX2(M(CVTDQ2PS)),
  .variant_f2 = XX2(M(CVTPD2DQ)),
},
[0xE8] = {
  .base = MM2(M(PSUBSB)),
  .variant_66 = XX2(M(PSUBSB)),
  .variant_f3 = NOVAR,
  .variant_f2 = NOVAR,
},
[0xE9] = {
  .base = MM2(M(PSUBSW)),
  .variant_66 = XX2(M(PSUBSW)),
  .variant_f3 = NOVAR,
  .variant_f2 = NOVAR,
},
[0xEA] = {
  .base = MM2(M(PMINSW)),
  .variant_66 = XX2(M(PMINSW)),
  .variant_f3 = NOVAR,
  .variant_f2 = NOVAR,
},
[0xEB] = {
  .base = MM2(M(POR)),
  .variant_66 = XX2(M(POR)),
  .variant_f3 = NOVAR,
  .variant_f2 = NOVAR,
},
[0xEC] = {
  .base = MM2(M(PADDSB)),
  .variant_66 = XX2(M(PADDSB)),
  .variant_f3 = NOVAR,
  .variant_f2 = NOVAR,
},
[0xED] = {
  .base = MM2(M(PADDSW)),
  .variant_66 = XX2(M(PADDSW)),
  .variant_f3 = NOVAR,
  .variant_f2 = NOVAR,
},
[0xEE] = {
  .base = MM2(M(PMAXSW)),
  .variant_66 = XX2(M(PMAXSW)),
  .variant_f3 = NOVAR,
  .variant_f2 = NOVAR,
},
[0xEF] = {
  .base = MM2(M(PXOR)),
  .variant_66 = XX2(M(PXOR)),
  .variant_f3 = NOVAR,
  .variant_f2 = NOVAR,
},
[0xF1] = {
  .base = MM2(M(PSLLW)),
  .variant_66 = XX2(M(PSLLW)),
  .variant_f3 = NOVAR,
  .variant_f2 = NOVAR,
},
[0xF2] = {
  .base = MM2(M(PSLLD)),
  .variant_66 = XX2(M(PSLLD)),
  .variant_f3 = NOVAR,
  .variant_f2 = NOVAR,
},
[0xF3] = {
  .base = MM2(M(PSLLQ)),
  .variant_66 = XX2(M(PSLLQ)),
  .variant_f3 = NOVAR,
  .variant_f2 = NOVAR,
},
[0xF4] = {
  .base = MM2(M(PMULUDQ)),
  .variant_66 = XX2(M(PMULUDQ)),
  .variant_f3 = NOVAR,
  .variant_f2 = NOVAR,
},
[0xF5] = {
  .base = MM2(M(PMADDWD)),
  .variant_66 = XX2(M(PMADDWD)),
  .variant_f3 = NOVAR,
  .variant_f2 = NOVAR,
},
[0xF6] = {
  .base = MM2(M(PSADBW)),
  .variant_66 = XX2(M(PSADBW)),
  .variant_f3 = NOVAR,
  .variant_f2 = NOVAR,
},
[0xF8] = {
  .base = MM2(M(PSUBB)),
  .variant_66 = XX2(M(PSUBB)),
  .variant_f3 = NOVAR,
  .variant_f2 = NOVAR,
},
[0xF9] = {
  .base = MM2(M(PSUBW)),
  .variant_66 = XX2(M(PSUBW)),
  .variant_f3 = NOVAR,
  .variant_f2 = NOVAR,
},
[0xFA] = {
  .base = MM2(M(PSUBD)),
  .variant_66 = XX2(M(PSUBD)),
  .variant_f3 = NOVAR,
  .variant_f2 = NOVAR,
},
[0xFB] = {
  .base = MM2(M(PSUBQ)),
  .variant_66 = XX2(M(PSUBQ)),
  .variant_f3 = NOVAR,
  .variant_f2 = NOVAR,
},
[0xFC] = {
  .base = MM2(M(PADDB)),
  .variant_66 = XX2(M(PADDB)),
  .variant_f3 = NOVAR,
  .variant_f2 = NOVAR,
},
[0xFD] = {
  .base = MM2(M(PADDW)),
  .variant_66 = XX2(M(PADDW)),
  .variant_f3 = NOVAR,
  .variant_f2 = NOVAR,
},
[0xFE] = {
  .base = MM2(M(PADDD)),
  .variant_66 = XX2(M(PADDD)),
  .variant_f3 = NOVAR,
  .variant_f2 = NOVAR,
}
};
