#include "tables.h"

#define M(x) X86DEC_MNEMONIC_##x
#define S(x) X86DEC_SHAPE_##x
#define V(mn, c, s0, s1, s2, mb) {(mn), (c), {(s0), (s1), (s2), 0}, (mb)}
#define V4(mn, c, s0, s1, s2, s3, mb) {(mn), (c), {(s0), (s1), (s2), (s3)}, (mb)}
#define NOVAR {0, 0, {0, 0, 0, 0}, 0}
#define VV S(VEX_VVVV)
#define VVG S(VEX_VVVV_GPR)

const X86decSseEntry x86dec_vex_0f[256] = {
[0x10] = { .base = V(M(VMOVUPS), 2, S(XMM_REG), S(XMM_OR_MEM), S(NONE), 0), .variant_66 = V(M(VMOVUPD), 2, S(XMM_REG), S(XMM_OR_MEM), S(NONE), 0), .variant_f3 = V(M(VMOVSS), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 32), .variant_f2 = V(M(VMOVSD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 64), },
[0x11] = { .base = V(M(VMOVUPS), 2, S(XMM_OR_MEM), S(XMM_REG), S(NONE), 0), .variant_66 = V(M(VMOVUPD), 2, S(XMM_OR_MEM), S(XMM_REG), S(NONE), 0), .variant_f3 = V(M(VMOVSS), 3, S(XMM_OR_MEM), VV, S(XMM_REG), 32), .variant_f2 = V(M(VMOVSD), 3, S(XMM_OR_MEM), VV, S(XMM_REG), 64), },
[0x12] = { .base = V(M(VUNPCKLPS), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_66 = V(M(VUNPCKLPD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0x13] = { .base = V(M(VUNPCKLPS), 2, S(XMM_OR_MEM), S(XMM_REG), S(NONE), 0), .variant_66 = V(M(VUNPCKLPD), 2, S(XMM_OR_MEM), S(XMM_REG), S(NONE), 0), },
[0x14] = { .base = V(M(VUNPCKLPS), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_66 = V(M(VUNPCKLPD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0x15] = { .base = V(M(VUNPCKHPS), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_66 = V(M(VUNPCKHPD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0x16] = { .base = V(M(VUNPCKHPS), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_66 = V(M(VUNPCKHPD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0x17] = { .base = V(M(VUNPCKHPS), 2, S(XMM_OR_MEM), S(XMM_REG), S(NONE), 0), .variant_66 = V(M(VUNPCKHPD), 2, S(XMM_OR_MEM), S(XMM_REG), S(NONE), 0), },
[0x28] = { .base = V(M(VMOVAPS), 2, S(XMM_REG), S(XMM_OR_MEM), S(NONE), 0), .variant_66 = V(M(VMOVAPD), 2, S(XMM_REG), S(XMM_OR_MEM), S(NONE), 0), },
[0x29] = { .base = V(M(VMOVAPS), 2, S(XMM_OR_MEM), S(XMM_REG), S(NONE), 0), .variant_66 = V(M(VMOVAPD), 2, S(XMM_OR_MEM), S(XMM_REG), S(NONE), 0), },
[0x2A] = { .variant_f3 = V(M(VCVTSI2SS), 3, S(XMM_REG), VV, S(GPR_OR_MEM), 32), .variant_f2 = V(M(VCVTSI2SD), 3, S(XMM_REG), VV, S(GPR_OR_MEM), 64), },
[0x2B] = { .base = V(M(VMOVNTPS), 2, S(XMM_OR_MEM), S(XMM_REG), S(NONE), 0), .variant_66 = V(M(VMOVNTPD), 2, S(XMM_OR_MEM), S(XMM_REG), S(NONE), 0), },
[0x2C] = { .variant_f3 = V(M(VCVTTSS2SI), 2, S(GPR_REG), S(XMM_OR_MEM), S(NONE), 32), .variant_f2 = V(M(VCVTTSD2SI), 2, S(GPR_REG), S(XMM_OR_MEM), S(NONE), 64), },
[0x2D] = { .variant_f3 = V(M(VCVTSS2SI), 2, S(GPR_REG), S(XMM_OR_MEM), S(NONE), 32), .variant_f2 = V(M(VCVTSD2SI), 2, S(GPR_REG), S(XMM_OR_MEM), S(NONE), 64), },
[0x2E] = { .base = V(M(VUCOMISS), 2, S(XMM_REG), S(XMM_OR_MEM), S(NONE), 32), .variant_66 = V(M(VUCOMISD), 2, S(XMM_REG), S(XMM_OR_MEM), S(NONE), 64), },
[0x2F] = { .base = V(M(VCOMISS), 2, S(XMM_REG), S(XMM_OR_MEM), S(NONE), 32), .variant_66 = V(M(VCOMISD), 2, S(XMM_REG), S(XMM_OR_MEM), S(NONE), 64), },
[0x50] = { .base = V(M(VMOVMSKPS), 2, S(R32_REG), S(XMM_RM), S(NONE), 0), .variant_66 = V(M(VMOVMSKPD), 2, S(R32_REG), S(XMM_RM), S(NONE), 0), },
[0x51] = { .base = V(M(VSQRTPS), 2, S(XMM_REG), S(XMM_OR_MEM), S(NONE), 0), .variant_66 = V(M(VSQRTPD), 2, S(XMM_REG), S(XMM_OR_MEM), S(NONE), 0), .variant_f3 = V(M(VSQRTSS), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 32), .variant_f2 = V(M(VSQRTSD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 64), },
[0x52] = { .base = V(M(VRCPPS), 2, S(XMM_REG), S(XMM_OR_MEM), S(NONE), 0), .variant_f3 = V(M(VRCPSS), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 32), },
[0x53] = { .base = V(M(VRSQRTPS), 2, S(XMM_REG), S(XMM_OR_MEM), S(NONE), 0), .variant_f3 = V(M(VRSQRTSS), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 32), },
[0x54] = { .base = V(M(VANDPS), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_66 = V(M(VANDPD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0x55] = { .base = V(M(VANDNPS), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_66 = V(M(VANDNPD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0x56] = { .base = V(M(VORPS), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_66 = V(M(VORPD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0x57] = { .base = V(M(VXORPS), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_66 = V(M(VXORPD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0x58] = { .base = V(M(VADDPS), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_66 = V(M(VADDPD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_f3 = V(M(VADDSS), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 32), .variant_f2 = V(M(VADDSD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 64), },
[0x59] = { .base = V(M(VMULPS), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_66 = V(M(VMULPD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_f3 = V(M(VMULSS), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 32), .variant_f2 = V(M(VMULSD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 64), },
[0x5A] = { .base = V(M(VCVTPS2PD), 2, S(XMM_REG), S(XMM_OR_MEM), S(NONE), 64), .variant_66 = V(M(VCVTPD2PS), 2, S(XMM_REG), S(XMM_OR_MEM), S(NONE), 0), .variant_f3 = V(M(VCVTSS2SD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 32), .variant_f2 = V(M(VCVTSD2SS), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 64), },
[0x5B] = { .base = V(M(VCVTDQ2PS), 2, S(XMM_REG), S(XMM_OR_MEM), S(NONE), 0), .variant_66 = V(M(VCVTPS2DQ), 2, S(XMM_REG), S(XMM_OR_MEM), S(NONE), 0), .variant_f3 = V(M(VCVTTPS2DQ), 2, S(XMM_REG), S(XMM_OR_MEM), S(NONE), 0), },
[0x5C] = { .base = V(M(VSUBPS), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_66 = V(M(VSUBPD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_f3 = V(M(VSUBSS), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 32), .variant_f2 = V(M(VSUBSD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 64), },
[0x5D] = { .base = V(M(VMINPS), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_66 = V(M(VMINPD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_f3 = V(M(VMINSS), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 32), .variant_f2 = V(M(VMINSD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 64), },
[0x5E] = { .base = V(M(VDIVPS), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_66 = V(M(VDIVPD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_f3 = V(M(VDIVSS), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 32), .variant_f2 = V(M(VDIVSD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 64), },
[0x5F] = { .base = V(M(VMAXPS), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_66 = V(M(VMAXPD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_f3 = V(M(VMAXSS), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 32), .variant_f2 = V(M(VMAXSD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 64), },
[0x60] = { .base = V(M(VPUNPCKLBW), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_66 = V(M(VPUNPCKLBW), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0x61] = { .base = V(M(VPUNPCKLWD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_66 = V(M(VPUNPCKLWD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0x62] = { .base = V(M(VPUNPCKLDQ), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_66 = V(M(VPUNPCKLDQ), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0x63] = { .base = V(M(VPACKSSWB), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_66 = V(M(VPACKSSWB), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0x64] = { .base = V(M(VPCMPGTB), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_66 = V(M(VPCMPGTB), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0x65] = { .base = V(M(VPCMPGTW), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_66 = V(M(VPCMPGTW), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0x66] = { .base = V(M(VPCMPGTD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_66 = V(M(VPCMPGTD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0x67] = { .base = V(M(VPACKUSWB), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_66 = V(M(VPACKUSWB), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0x68] = { .base = V(M(VPUNPCKHBW), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_66 = V(M(VPUNPCKHBW), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0x69] = { .base = V(M(VPUNPCKHWD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_66 = V(M(VPUNPCKHWD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0x6A] = { .base = V(M(VPUNPCKHDQ), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_66 = V(M(VPUNPCKHDQ), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0x6B] = { .base = V(M(VPACKSSDW), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_66 = V(M(VPACKSSDW), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0x6C] = { .variant_66 = V(M(VPUNPCKLQDQ), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0x6D] = { .variant_66 = V(M(VPUNPCKHQDQ), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0x6F] = { .base = V(M(VMOVDQU), 2, S(XMM_REG), S(XMM_OR_MEM), S(NONE), 0), .variant_66 = V(M(VMOVDQA), 2, S(XMM_REG), S(XMM_OR_MEM), S(NONE), 0), },
[0x70] = { .base = V(M(VPSHUFD), 3, S(XMM_REG), S(XMM_OR_MEM), S(IMM8), 0), .variant_66 = V(M(VPSHUFD), 3, S(XMM_REG), S(XMM_OR_MEM), S(IMM8), 0), .variant_f3 = V(M(VPSHUFHW), 3, S(XMM_REG), S(XMM_OR_MEM), S(IMM8), 0), .variant_f2 = V(M(VPSHUFLW), 3, S(XMM_REG), S(XMM_OR_MEM), S(IMM8), 0), },
[0x74] = { .base = V(M(VPCMPEQB), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_66 = V(M(VPCMPEQB), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0x75] = { .base = V(M(VPCMPEQW), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_66 = V(M(VPCMPEQW), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0x76] = { .base = V(M(VPCMPEQD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_66 = V(M(VPCMPEQD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0x77] = { .base = V(M(VZEROUPPER), 0, S(NONE), S(NONE), S(NONE), 0), },
[0x7C] = { .variant_66 = V(M(VHADDPD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_f2 = V(M(VHADDPS), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0x7D] = { .variant_66 = V(M(VHSUBPD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_f2 = V(M(VHSUBPS), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0x7E] = { .base = V(M(VMOVQ), 2, S(XMM_REG), S(XMM_OR_MEM), S(NONE), 64), .variant_66 = V(M(VMOVQ), 2, S(XMM_REG), S(XMM_OR_MEM), S(NONE), 64), .variant_f3 = V(M(VMOVQ), 2, S(XMM_REG), S(XMM_OR_MEM), S(NONE), 64), },
[0x7F] = { .base = V(M(VMOVDQU), 2, S(XMM_OR_MEM), S(XMM_REG), S(NONE), 0), .variant_66 = V(M(VMOVDQA), 2, S(XMM_OR_MEM), S(XMM_REG), S(NONE), 0), },
[0xC2] = { .base = V4(M(VCMPPS), 4, S(XMM_REG), VV, S(XMM_OR_MEM), S(IMM8), 0), .variant_66 = V4(M(VCMPPD), 4, S(XMM_REG), VV, S(XMM_OR_MEM), S(IMM8), 0), .variant_f3 = V4(M(VCMPSS), 4, S(XMM_REG), VV, S(XMM_OR_MEM), S(IMM8), 32), .variant_f2 = V4(M(VCMPSD), 4, S(XMM_REG), VV, S(XMM_OR_MEM), S(IMM8), 64), },
[0xC6] = { .base = V4(M(VSHUFPS), 4, S(XMM_REG), VV, S(XMM_OR_MEM), S(IMM8), 0), .variant_66 = V4(M(VSHUFPD), 4, S(XMM_REG), VV, S(XMM_OR_MEM), S(IMM8), 0), },
[0xD0] = { .variant_66 = V(M(VADDSUBPD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_f2 = V(M(VADDSUBPS), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0xD1] = { .base = V(M(VPSRLW), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_66 = V(M(VPSRLW), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0xD2] = { .base = V(M(VPSRLD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_66 = V(M(VPSRLD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0xD3] = { .base = V(M(VPSRLQ), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_66 = V(M(VPSRLQ), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0xD4] = { .base = V(M(VPADDQ), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_66 = V(M(VPADDQ), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0xD5] = { .base = V(M(VPMULLW), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_66 = V(M(VPMULLW), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0xD8] = { .base = V(M(VPSUBUSB), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_66 = V(M(VPSUBUSB), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0xD9] = { .base = V(M(VPSUBUSW), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_66 = V(M(VPSUBUSW), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0xDA] = { .base = V(M(VPMINUB), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_66 = V(M(VPMINUB), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0xE0] = { .base = V(M(VPAVGB), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_66 = V(M(VPAVGB), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0xE1] = { .base = V(M(VPSRAW), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_66 = V(M(VPSRAW), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0xE2] = { .base = V(M(VPSRAD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_66 = V(M(VPSRAD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0xE3] = { .base = V(M(VPAVGW), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_66 = V(M(VPAVGW), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0xE4] = { .base = V(M(VPMULHUW), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_66 = V(M(VPMULHUW), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0xE5] = { .base = V(M(VPMULHW), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_66 = V(M(VPMULHW), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0xE6] = { .base = NOVAR, .variant_66 = V(M(VCVTTPD2DQ), 2, S(XMM_REG), S(XMM_OR_MEM), S(NONE), 0), .variant_f3 = V(M(VCVTDQ2PD), 2, S(XMM_REG), S(XMM_OR_MEM), S(NONE), 0), .variant_f2 = V(M(VCVTPD2DQ), 2, S(XMM_REG), S(XMM_OR_MEM), S(NONE), 0), },
[0xE8] = { .base = V(M(VPSUBSB), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_66 = V(M(VPSUBSB), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0xE9] = { .base = V(M(VPSUBSW), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_66 = V(M(VPSUBSW), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0xEA] = { .base = V(M(VPMINSW), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_66 = V(M(VPMINSW), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0xEB] = { .base = V(M(VPOR), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_66 = V(M(VPOR), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0xEC] = { .base = V(M(VPADDSB), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_66 = V(M(VPADDSB), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0xED] = { .base = V(M(VPADDSW), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_66 = V(M(VPADDSW), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0xEE] = { .base = V(M(VPMAXSW), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_66 = V(M(VPMAXSW), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0xEF] = { .base = V(M(VPXOR), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_66 = V(M(VPXOR), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0xF1] = { .base = V(M(VPSLLW), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_66 = V(M(VPSLLW), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0xF2] = { .base = V(M(VPSLLD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_66 = V(M(VPSLLD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0xF3] = { .base = V(M(VPSLLQ), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_66 = V(M(VPSLLQ), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0xF4] = { .base = V(M(VPMULUDQ), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_66 = V(M(VPMULUDQ), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0xF5] = { .base = V(M(VPMADDWD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_66 = V(M(VPMADDWD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0xF6] = { .base = V(M(VPSADBW), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_66 = V(M(VPSADBW), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0xF8] = { .base = V(M(VPSUBB), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_66 = V(M(VPSUBB), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0xF9] = { .base = V(M(VPSUBW), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_66 = V(M(VPSUBW), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0xFA] = { .base = V(M(VPSUBD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_66 = V(M(VPSUBD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0xFB] = { .base = V(M(VPSUBQ), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_66 = V(M(VPSUBQ), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0xFC] = { .base = V(M(VPADDB), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_66 = V(M(VPADDB), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0xFD] = { .base = V(M(VPADDW), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_66 = V(M(VPADDW), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0xFE] = { .base = V(M(VPADDD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), .variant_66 = V(M(VPADDD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
};

const X86decSseEntry x86dec_vex_0f38[256] = {
[0x00] = { .variant_66 = V(M(VPSHUFB), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0x01] = { .variant_66 = V(M(VPHADDW), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0x02] = { .variant_66 = V(M(VPHADDD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0x03] = { .variant_66 = V(M(VPHADDSW), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0x04] = { .variant_66 = V(M(VPMADDUBSW), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0x05] = { .variant_66 = V(M(VPHSUBW), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0x06] = { .variant_66 = V(M(VPHSUBD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0x07] = { .variant_66 = V(M(VPHSUBSW), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0x08] = { .variant_66 = V(M(VPSIGNB), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0x09] = { .variant_66 = V(M(VPSIGNW), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0x0A] = { .variant_66 = V(M(VPSIGND), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0x0B] = { .variant_66 = V(M(VPMULHRSW), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0x0C] = { .variant_66 = V(M(VPERMILPS), 3, S(XMM_REG), S(XMM_OR_MEM), S(IMM8), 0), },
[0x0D] = { .variant_66 = V(M(VPERMILPD), 3, S(XMM_REG), S(XMM_OR_MEM), S(IMM8), 0), },
[0x0E] = { .variant_66 = V(M(VTESTPS), 2, S(XMM_REG), S(XMM_OR_MEM), S(NONE), 0), },
[0x0F] = { .variant_66 = V(M(VTESTPD), 2, S(XMM_REG), S(XMM_OR_MEM), S(NONE), 0), },
[0x10] = { .variant_66 = V4(M(VPBLENDVB), 4, S(XMM_REG), VV, S(XMM_OR_MEM), S(IMPLICIT_XMM0), 0), },
[0x14] = { .variant_66 = V4(M(VBLENDVPS), 4, S(XMM_REG), VV, S(XMM_OR_MEM), S(IMPLICIT_XMM0), 0), },
[0x15] = { .variant_66 = V4(M(VBLENDVPD), 4, S(XMM_REG), VV, S(XMM_OR_MEM), S(IMPLICIT_XMM0), 0), },
[0x17] = { .variant_66 = V(M(VPTEST), 2, S(XMM_REG), S(XMM_OR_MEM), S(NONE), 0), },
[0x18] = { .variant_66 = V(M(VBROADCASTSS), 2, S(XMM_REG), S(MEM32_RM), S(NONE), 0), },
[0x19] = { .variant_66 = V(M(VBROADCASTSD), 2, S(XMM_REG), S(MEM64_RM), S(NONE), 0), },
[0x1A] = { .variant_66 = V(M(VBROADCASTF128), 2, S(YMM_REG), S(MEM_RM), S(NONE), 128), },
[0x1C] = { .variant_66 = V(M(VPABSB), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0x1D] = { .variant_66 = V(M(VPABSW), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0x1E] = { .variant_66 = V(M(VPABSD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0x20] = { .variant_66 = V(M(VPMOVSXBW), 2, S(XMM_REG), S(XMM_OR_MEM), S(NONE), 64), },
[0x21] = { .variant_66 = V(M(VPMOVSXBD), 2, S(XMM_REG), S(XMM_OR_MEM), S(NONE), 32), },
[0x22] = { .variant_66 = V(M(VPMOVSXBQ), 2, S(XMM_REG), S(XMM_OR_MEM), S(NONE), 16), },
[0x23] = { .variant_66 = V(M(VPMOVSXWD), 2, S(XMM_REG), S(XMM_OR_MEM), S(NONE), 32), },
[0x24] = { .variant_66 = V(M(VPMOVSXWQ), 2, S(XMM_REG), S(XMM_OR_MEM), S(NONE), 16), },
[0x25] = { .variant_66 = V(M(VPMOVSXDQ), 2, S(XMM_REG), S(XMM_OR_MEM), S(NONE), 32), },
[0x28] = { .variant_66 = V(M(VPMULDQ), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0x29] = { .variant_66 = V(M(VPCMPEQQ), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0x2A] = { .variant_66 = V(M(VMOVNTDQA), 2, S(XMM_REG), S(XMM_OR_MEM), S(NONE), 0), },
[0x2B] = { .variant_66 = V(M(VPACKUSDW), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0x30] = { .variant_66 = V(M(VPMOVZXBW), 2, S(XMM_REG), S(XMM_OR_MEM), S(NONE), 64), },
[0x31] = { .variant_66 = V(M(VPMOVZXBD), 2, S(XMM_REG), S(XMM_OR_MEM), S(NONE), 32), },
[0x32] = { .variant_66 = V(M(VPMOVZXBQ), 2, S(XMM_REG), S(XMM_OR_MEM), S(NONE), 16), },
[0x33] = { .variant_66 = V(M(VPMOVZXWD), 2, S(XMM_REG), S(XMM_OR_MEM), S(NONE), 32), },
[0x34] = { .variant_66 = V(M(VPMOVZXWQ), 2, S(XMM_REG), S(XMM_OR_MEM), S(NONE), 16), },
[0x35] = { .variant_66 = V(M(VPMOVZXDQ), 2, S(XMM_REG), S(XMM_OR_MEM), S(NONE), 32), },
[0x37] = { .variant_66 = V(M(VPCMPGTQ), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0x3C] = { .variant_66 = V(M(VPMAXSB), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0x3D] = { .variant_66 = V(M(VPMAXSD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0x3E] = { .variant_66 = V(M(VPMAXUD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0x3F] = { .variant_66 = V(M(VPMAXUW), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0x40] = { .variant_66 = V(M(VPMULLD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0x41] = { .variant_66 = V(M(VPHMINPOSUW), 2, S(XMM_REG), S(XMM_OR_MEM), S(NONE), 0), },
[0x45] = { .variant_66 = V(M(VPSRLVD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0x47] = { .variant_66 = V(M(VPSLLVD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0x58] = { .variant_66 = V(M(VPBROADCASTD), 2, S(XMM_REG), S(R32_OR_MEM), S(NONE), 0), },
[0x59] = { .variant_66 = V(M(VPBROADCASTQ), 2, S(XMM_REG), S(GPR_OR_MEM), S(NONE), 0), },
[0x78] = { .variant_66 = V(M(VPBROADCASTB), 2, S(XMM_REG), S(GPR8_OR_MEM), S(NONE), 0), },
[0x79] = { .variant_66 = V(M(VPBROADCASTB), 2, S(XMM_REG), S(XMM_OR_MEM), S(NONE), 16), },
[0x8C] = { .variant_66 = V(M(VPERMD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0x8D] = { .variant_66 = V(M(VPERMPS), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0x98] = { .variant_66 = V(M(VFMADD132PS), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0x99] = { .variant_66 = V(M(VFMADD132PD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0x9A] = { .variant_66 = V(M(VFMADD132SS), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 32), },
[0x9B] = { .variant_66 = V(M(VFMADD132SD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 64), },
[0x9C] = { .variant_66 = V(M(VFMSUB132PS), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0x9D] = { .variant_66 = V(M(VFMSUB132PD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0x9E] = { .variant_66 = V(M(VFMSUB132SS), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 32), },
[0x9F] = { .variant_66 = V(M(VFMSUB132SD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 64), },
[0xA8] = { .variant_66 = V(M(VFMADD213PS), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0xA9] = { .variant_66 = V(M(VFMADD213PD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0xAA] = { .variant_66 = V(M(VFMADD213SS), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 32), },
[0xAB] = { .variant_66 = V(M(VFMADD213SD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 64), },
[0xAC] = { .variant_66 = V(M(VFMSUB213PS), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0xAD] = { .variant_66 = V(M(VFMSUB213PD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0xAE] = { .variant_66 = V(M(VFMSUB213SS), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 32), },
[0xAF] = { .variant_66 = V(M(VFMSUB213SD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 64), },
[0xB8] = { .variant_66 = V(M(VFMADD231PS), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0xB9] = { .variant_66 = V(M(VFMADD231PD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0xBA] = { .variant_66 = V(M(VFMADD231SS), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 32), },
[0xBB] = { .variant_66 = V(M(VFMADD231SD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 64), },
[0xBC] = { .variant_66 = V(M(VFMSUB231PS), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0xBD] = { .variant_66 = V(M(VFMSUB231PD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0xBE] = { .variant_66 = V(M(VFMSUB231SS), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 32), },
[0xBF] = { .variant_66 = V(M(VFMSUB231SD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 64), },
[0xD8] = { .variant_66 = V(M(VFNMADD132PS), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0xD9] = { .variant_66 = V(M(VFNMADD132PD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0xDA] = { .variant_66 = V(M(VFNMADD132SS), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 32), },
[0xE8] = { .variant_66 = V(M(VFNMADD213PS), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0xE9] = { .variant_66 = V(M(VFNMADD213PD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0xEA] = { .variant_66 = V(M(VFNMADD213SS), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 32), },
[0xEB] = { .variant_66 = V(M(VFNMADD213SD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 64), },
[0xEC] = { .variant_66 = V(M(VFNMSUB213PS), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0xED] = { .variant_66 = V(M(VFNMSUB213PD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0xEE] = { .variant_66 = V(M(VFNMSUB213SS), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 32), },
[0xEF] = { .variant_66 = V(M(VFNMSUB213SD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 64), },
[0xF8] = { .variant_66 = V(M(VFNMADD231PS), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0xF9] = { .variant_66 = V(M(VFNMADD231PD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0xFA] = { .variant_66 = V(M(VFNMADD231SS), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 32), },
[0xFB] = { .variant_66 = V(M(VFNMADD231SD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 64), },
[0xFC] = { .variant_66 = V(M(VFNMSUB231PS), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0xFD] = { .variant_66 = V(M(VFNMSUB231PD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 0), },
[0xFE] = { .variant_66 = V(M(VFNMSUB231SS), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 32), },
[0xFF] = { .variant_66 = V(M(VFNMSUB231SD), 3, S(XMM_REG), VV, S(XMM_OR_MEM), 64), },
[0x13] = { .variant_66 = V(M(VCVTPH2PS), 2, S(XMM_REG), S(XMM_OR_MEM), S(NONE), 64), },
[0xF2] = { .base = V(M(ANDN), 3, S(GPR_REG), VVG, S(GPR_OR_MEM), 0), },
[0xF5] = { .base = V(M(BZHI), 3, S(GPR_REG), VVG, S(GPR_OR_MEM), 0), .variant_f3 = V(M(PEXT), 3, S(GPR_REG), VVG, S(GPR_OR_MEM), 0), .variant_f2 = V(M(PDEP), 3, S(GPR_REG), VVG, S(GPR_OR_MEM), 0), },
[0xF6] = { .variant_f2 = V(M(MULX), 3, S(GPR_REG), VVG, S(GPR_OR_MEM), 0), },
[0xF7] = { .base = V(M(BEXTR), 3, S(GPR_REG), VVG, S(GPR_OR_MEM), 0), .variant_66 = V(M(SHLX), 3, S(GPR_REG), VVG, S(GPR_OR_MEM), 0), .variant_f3 = V(M(SARX), 3, S(GPR_REG), VVG, S(GPR_OR_MEM), 0), .variant_f2 = V(M(SHRX), 3, S(GPR_REG), VVG, S(GPR_OR_MEM), 0), },
};

const X86decSseEntry x86dec_vex_0f3a[256] = {
[0x00] = { .variant_66 = V(M(VPERMQ), 3, S(XMM_REG), S(XMM_OR_MEM), S(IMM8), 0), },
[0x06] = { .variant_66 = V4(M(VPERM2F128), 4, S(YMM_REG), VV, S(YMM_OR_MEM), S(IMM8), 0), },
[0x08] = { .variant_66 = V(M(VROUNDPS), 3, S(XMM_REG), S(XMM_OR_MEM), S(IMM8), 0), },
[0x09] = { .variant_66 = V(M(VROUNDPD), 3, S(XMM_REG), S(XMM_OR_MEM), S(IMM8), 0), },
[0x0A] = { .variant_66 = V4(M(VROUNDSS), 4, S(XMM_REG), VV, S(XMM_OR_MEM), S(IMM8), 32), },
[0x0B] = { .variant_66 = V4(M(VROUNDSD), 4, S(XMM_REG), VV, S(XMM_OR_MEM), S(IMM8), 64), },
[0x0C] = { .variant_66 = V4(M(VBLENDPS), 4, S(XMM_REG), VV, S(XMM_OR_MEM), S(IMM8), 0), },
[0x0D] = { .variant_66 = V4(M(VBLENDPD), 4, S(XMM_REG), VV, S(XMM_OR_MEM), S(IMM8), 0), },
[0x0E] = { .variant_66 = V4(M(VPBLENDW), 4, S(XMM_REG), VV, S(XMM_OR_MEM), S(IMM8), 0), },
[0x0F] = { .base = V4(M(VPALIGNR), 4, S(XMM_REG), VV, S(XMM_OR_MEM), S(IMM8), 0), .variant_66 = V4(M(VPALIGNR), 4, S(XMM_REG), VV, S(XMM_OR_MEM), S(IMM8), 0), },
[0x14] = { .variant_66 = V(M(VPEXTRB), 3, S(R32_OR_MEM), S(XMM_REG), S(IMM8), 0), },
[0x15] = { .variant_66 = V(M(VPEXTRW), 3, S(R32_OR_MEM), S(XMM_REG), S(IMM8), 0), },
[0x16] = { .variant_66 = V(M(VPEXTRD), 3, S(R32_OR_MEM), S(XMM_REG), S(IMM8), 0), },
[0x17] = { .variant_66 = V(M(VEXTRACTPS), 3, S(R32_OR_MEM), S(XMM_REG), S(IMM8), 0), },
[0x18] = { .variant_66 = V4(M(VINSERTF128), 4, S(YMM_REG), VV, S(XMM_OR_MEM), S(IMM8), 128), },
[0x19] = { .variant_66 = V(M(VEXTRACTF128), 3, S(XMM_OR_MEM), S(YMM_REG), S(IMM8), 128), },
[0x1D] = { .variant_66 = V(M(VCVTPS2PH), 3, S(XMM_OR_MEM), S(XMM_REG), S(IMM8), 0), },
[0x20] = { .variant_66 = V(M(VPINSRB), 3, S(XMM_REG), VV, S(R32_OR_MEM), 0), },
[0x21] = { .variant_66 = V4(M(VINSERTPS), 4, S(XMM_REG), VV, S(XMM_OR_MEM), S(IMM8), 32), },
[0x22] = { .variant_66 = V(M(VPINSRD), 3, S(XMM_REG), VV, S(R32_OR_MEM), 0), },
[0x40] = { .variant_66 = V4(M(VDPPS), 4, S(XMM_REG), VV, S(XMM_OR_MEM), S(IMM8), 0), },
[0x41] = { .variant_66 = V4(M(VDPPD), 4, S(XMM_REG), VV, S(XMM_OR_MEM), S(IMM8), 0), },
[0x42] = { .variant_66 = V4(M(VMPSADBW), 4, S(XMM_REG), VV, S(XMM_OR_MEM), S(IMM8), 0), },
[0x44] = { .variant_66 = V4(M(VPCLMULQDQ), 4, S(XMM_REG), VV, S(XMM_OR_MEM), S(IMM8), 0), },
[0x60] = { .variant_66 = V(M(VPCMPESTRM), 3, S(XMM_REG), S(XMM_OR_MEM), S(IMM8), 0), },
[0x61] = { .variant_66 = V(M(VPCMPESTRI), 3, S(XMM_REG), S(XMM_OR_MEM), S(IMM8), 0), },
[0x62] = { .variant_66 = V(M(VPCMPISTRM), 3, S(XMM_REG), S(XMM_OR_MEM), S(IMM8), 0), },
[0x63] = { .variant_66 = V(M(VPCMPISTRI), 3, S(XMM_REG), S(XMM_OR_MEM), S(IMM8), 0), },
[0xF0] = { .variant_f2 = V(M(RORX), 3, S(GPR_REG), S(GPR_OR_MEM), S(IMM8), 0), },
};
